spring:
  application:
    name: notification-service

# kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
#        spring.json.type.mapping: event:com.maniraj.order.event.OrderPlacedEvent

#        # Trust the package where OrderPlacedEvent actually lives
        spring.json.trusted.packages: "com.maniraj.notification.model"
#        # Set the default type to the actual class
        spring.json.value.default.type: com.maniraj.order.event.OrderPlacedEvent
#        # Disable type headers if not using them
        spring.json.use.type.headers: false

  # Mail configuration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 1a5e245d5b2a97
    password: c85ad32590427c

server:
  port: 8083